on:
  push:
    branches: [main]
    # schedule:
    #   - cron: 5 * * * *
jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get artifact value
        uses: actions/download-artifact@v3
        with:
          name: commit-id
      - name: Update Commit Value
        run: |-
          chmod +x ./src/monitor_unit/get_commit_value.sh
          chmod +x ./src/monitor_unit/trigger_workflow.sh
          export SECRET_KEY=${{ secrets.SECRET_KEY }}
          ./src/monitor_unit/get_commit_value.sh
          file1 = "./commit-id.txt"
          file2 = "./commit_id.txt"
          cat ./commit-id.txt
          cat ./commit_id.txt
          if cmp -s "$file1" "$file2"; then
            echo "No changes!"
          else
            ./src/monitor_unit/trigger_workflow.sh
          # if [[ "$prev" == "$cur" ]] then
          #   echo "No change!"
          # else
          #   echo "Change!"
      - uses: actions/upload-artifact@v3
        with:
          name: commit-id
          path: ./commit_id.txt
