on:
  push:
    branches: [main]
    # schedule:
    #   - cron: 5 * * * *
jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check commit value against last value
        run: |-
          ls ./src/monitor_unit
          chmod +x ./src/monitor_unit/compare_commits.sh
          export SECRET_KEY=${{ secrets.SECRET_KEY }}
          ./src/monitor_unit/compare_commits.sh
      - name: Update Commit Value
        run: |-
          chmod +x ./src/monitor_unit/update_commit_value.sh
          ./src/monitor_unit/update_commit_value.sh
