on:
  schedule:
    - cron: 0 */6 * * *
permissions:
  id-token: write
  contents: write
  actions: write
  checks: write
  deployments: write
  discussions: write
  issues: write
  pages: read
  packages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write
jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check commit value against last value
        run: |-
          ls ./src/monitor_unit
          chmod +x ./src/monitor_unit/compare_commits.sh
          export SECRET_KEY=${{ secrets.SECRET_KEY_2 }}
          ./src/monitor_unit/compare_commits.sh
      - name: Update Commit Value
        run: |-
          chmod +x ./src/monitor_unit/update_commit_value.sh
          export SECRET_KEY=${{ secrets.SECRET_KEY_2 }}
          ./src/monitor_unit/update_commit_value.sh
    # - name: Push changes
    #   uses: ad-m/github-push-action@master
    #   with:
    #     github_token: ${{ secrets.SECRET_KEY_2 }}
    #     branch: ${{ github.ref }}
