on:
  push:
    branches: ["main", "actions"]

jobs:
  
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Current Repository
        uses: actions/checkout@v3

      - name: Clone and shift tests
        run: |
          cd src/workflow_utils
          chmod +x setup.sh
          ls
          setup.sh
