'on':
  push:
    branches:
      - main
      - feature/send_reports_over_email
  workflow_dispatch: null
jobs:
  run-tests:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        pg_version:
          - 15
    services:
      postgres:
        image: 'postgres:${{ matrix.pg_version }}'
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - '5432:5432'
        options: >-
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Checkout Current Repository
        uses: actions/checkout@v3
      - name: Clone and shift tests
        run: cd src/workflow_utils && chmod +x setup.sh && ./setup.sh
      - name: check_val
        run: ls src/ && ls ../
      - uses: actions/upload-artifact@v3
        with:
          name: test-log
          path: ./src/final_report.log
      - uses: actions/upload-artifact@v3
        with:
          name: broken-links
          path: ./src/broken_urls.log
      - uses: actions/upload-artifact@v3
        with:
          name: failure_logs
          path: ./src/failed_tests.log
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          # Specify connection via URL (replaces server_address, server_port, secure,
          # username and password)
          #
          # Format:
          #
          #  * smtp://user:password@server:port
          #  * smtp+starttls://user:password@server:port
          connection_url: ${{secrets.MAIL_CONNECTION}}
          # Required mail server address if not connection_url:
          server_address: smtp.gmail.com
          # Server port, default 25:
          server_port: 465
          # Optional whether this connection use TLS (default is true if server_port is 465)
          secure: true
          # Optional (recommended) mail server username:
          username: ${{secrets.MAIL_USERNAME}}
          # Optional (recommended) mail server password:
          password: ${{secrets.MAIL_PASSWORD}}
          # Required mail subject:
          subject: Github Actions job result
          # Required recipients' addresses:
          to: destrex271@gmail.com, akshatdev2711@gmail.com
          # Required sender full name (address can be skipped):
          from: Pgweb Testing Harness # <user@example.com>
          # Optional plain body:
          body: Build job of ${{github.repository}} completed successfully!
          # Optional carbon copy recipients:
          # cc: kyloren@example.com,leia@example.com
          # Optional blind carbon copy recipients:
          # bcc: r2d2@example.com,hansolo@example.com
          # Optional recipient of the email response:
          # reply_to: luke@example.com
          # Optional Message ID this message is replying to:
          # in_reply_to: <random-luke@example.com>
          # Optional unsigned/invalid certificates allowance:
          # ignore_cert: true
          # Optional converting Markdown to HTML (set content_type to text/html too):
          # convert_markdown: true
          # Optional attachments:
          attachments: ./src/failure_tests.log
          # Optional priority: 'high', 'normal' (default) or 'low'
          # priority: low


# send_mail:
#   needs: run-tests
#   runs-on: ubuntu-20.04
#   steps:
#     - uses: xSAVIKx/artifact-exists-action@v0
#       id: chek
#       with: 
#         name: 'broken-links'
#     - name: Download Artifact
#       uses: actions/download-artifact@v3
#       with:
#         name: broken-links
#     - name: Send mail
#       if: steps.chek.exists == true
#       uses: dawidd6/action-send-mail@v3
#       with:
#         connection_url: ${{secrets.MAIL_CONNECTION}}
#         server_address: smtp.gmail.com
#         server_port: 465
#         secure: true
#         username: ${{secrets.MAIL_USERNAME}}
#         password: ${{secrets.MAIL_PASSWORD}}
#         subject: Github Actions job result
#         to: obiwan@example.com,yoda@example.com
#         from: pgweb-testing-harness@gmail.com # <user@example.com>
#         body: Build job of ${{github.repository}} completed successfully!
#         html_body: file://README.html
#         cc: kyloren@example.com,leia@example.com
#         bcc: r2d2@example.com,hansolo@example.com
#         reply_to: luke@example.com
#         in_reply_to: <random-luke@example.com>
#         ignore_cert: true
#         convert_markdown: true
#         attachments: 
#         priority: low
